export const INCREMENT_VALUE_1 = "INCREMENT_VALUE1";
export const DECREASE_VALUE_1 = "DECREASE_VALUE1";

export const INCREMENT_VALUE_2 = "INCREMENT_VALUE2";
export const DECREASE_VALUE_2 = "DECREASE_VALUE2";
